# -*- coding: utf-8 -*-
"""Genetico_V3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NviVMeOWU7fe4OjoS3EpYMd6XCpu6Ebl
"""



import pandas as pd
import numpy as np
import random
from deap import base, creator, tools, algorithms
import pandas as pd

from scipy.interpolate import interp1d
# =========================================================
# 1. CARGA DE DATOS
# =========================================================
# Asegúrate de que los nombres de los archivos coincidan exactamente
df_lib = pd.read_excel("R_observ.xlsx")
df_cambio = pd.read_csv("Cambio_almacenamiento_historico.csv")
df_total = pd.read_csv("DataSetExport-Total Storage.csv")
df_evap = pd.read_csv("DataSetExport-Evaporation,accumltd.Daily Evaporation - mm@08461200-Instantaneous-mm-20260622185804.csv", skiprows=1)
df_batimetria = pd.read_csv('tabla_elevacion_volumen_FINAL.csv')
# =========================================================
# 2. PREPARACIÓN Y LIMPIEZA
# =========================================================


def preparar_ventana_semanal(df_lib, df_cambio, df_total, df_evap, df_batimetria, fecha_inicio_str, semanas):
    """
    Versión con Área Dinámica: Calcula la evaporación basándose en el volumen de la presa.
    """
    # 1. Limpieza de datos (igual a tu lógica original)
    dataframes = [df_lib.copy(), df_cambio.copy(), df_total.copy(), df_evap.copy()]
    for i, df in enumerate(dataframes):
        df.columns = df.columns.str.strip()
        if 'Timestamp (UTC-06:00)' in df.columns: df.rename(columns={'Timestamp (UTC-06:00)': 'Fecha'}, inplace=True)
        if 'Value (mm)' in df.columns: df.rename(columns={'Value (mm)': 'Evaporacion_mm'}, inplace=True)
        
        if 'Fecha' in df.columns:
            df['Fecha'] = pd.to_datetime(df['Fecha'], errors='coerce')
            df = df.dropna(subset=['Fecha']).set_index('Fecha')
        dataframes[i] = df

    df_lib_p, df_cambio_p, df_total_p, df_evap_p = dataframes

    # 2. Preparar el interpolador de área (Volumen TCM -> Área km2)
    # Calculamos área (km2) como dV/dh (o aproximación dV/dV)
    # Nota: Tu CSV tiene volumen en TCM y Mm3, usaremos volumen_TCM
    vol = df_batimetria['volume_TCM'].values
    # Calculamos área como el cambio de volumen entre pasos de elevación
    # dV_TCM / dh_m = área en km2
    area = np.gradient(df_batimetria['volume_TCM'], df_batimetria['elevation_m'])
    f_area = interp1d(vol, area, kind='linear', fill_value="extrapolate")

    # 3. Agrupación Semanal
    lib_semanal = df_lib_p['Valor'].resample('W-SUN').mean() * 604.8
    cambio_semanal = df_cambio_p['Value (TCM)'].resample('W-SUN').sum()
    total_semanal = df_total_p['Value (TCM)'].resample('W-SUN').first()
    evap_semanal_mm = df_evap_p['Evaporacion_mm'].resample('W-SUN').sum()

    # 4. Cálculo de Evaporación Dinámica
    # Obtenemos el volumen histórico para cada semana y calculamos el área
    volumen_hist = total_semanal.reindex(evap_semanal_mm.index).ffill()
    area_semanal = f_area(volumen_hist)
    evap_semanal_tcm = evap_semanal_mm * area_semanal

    # 5. Extracción de ventana
    fecha_inicio = pd.to_datetime(fecha_inicio_str)
    R_obs = lib_semanal.loc[fecha_inicio:].head(semanas).values
    Delta_S_obs = cambio_semanal.loc[fecha_inicio:].head(semanas).values
    #Evap_TCM = evap_semanal_tcm.loc[fecha_inicio:].head(semanas).values
    
    # Condición Inicial
    S_inicial = total_semanal.loc[:fecha_inicio].iloc[-1]

    return R_obs, Delta_S_obs, S_inicial #,Evap_TCM
# Define tu ventana de estrés hídrico
fecha_inicio_str = '2024-01-01'
"""R_obs, Delta_S_obs, Evap_TCM, S_inicial = preparar_ventana_semanal(
    df_lib, df_cambio, df_total, df_evap, df_batimetria, fecha_inicio_str
)"""

# =========================================================
# 3. PARÁMETROS DEL MODELO (Basado en el Documento)
# =========================================================

T = 27
R_obs, Delta_S_obs, S_inicial = preparar_ventana_semanal(
    df_lib, df_cambio, df_total, df_evap, df_batimetria, fecha_inicio_str,T
)

S_max = 3387000.0          # TCM
S_min = 0.25 * S_max       # Almacenamiento crítico (25%)
mediana_R = np.median(R_obs)
delta_u = 0.25 * mediana_R # Ajuste base
u_max = 2 * delta_u

# Niveles discretos permitidos L=5
NIVELES_PERMITIDOS = [-2*delta_u, -delta_u, 0.0, delta_u, 2*delta_u]

# =========================================================
# 4. CONFIGURACIÓN DE DEAP (Algoritmo Genético)
# =========================================================
# Limpieza de caché (útil si usas Jupyter Notebook)
if 'FitnessMin' in creator.__dict__:
    del creator.FitnessMin
if 'Individual' in creator.__dict__:
    del creator.Individual

creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", list, fitness=creator.FitnessMin)

toolbox = base.Toolbox()
toolbox.register("attr_level", random.choice, NIVELES_PERMITIDOS)
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.attr_level, n=T)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

# =========================================================
# 5. FUNCIÓN FITNESS (Storage Resilience Score - SRS)
# =========================================================
def evaluar_srs(individuo):
    cromosoma_u = np.array(individuo)
    S_opt = np.zeros(T + 1)
    S_opt[0] = S_inicial

    # RESTRICCIÓN DURA: Balance de liberación acumulada (Límite 10%)
    if abs(np.sum(cromosoma_u)) > 0.10 * np.sum(R_obs):
        return (float('1e10'),)

    for t in range(T):
        
       
        # Transición de estado
        S_opt[t+1] = S_opt[t] + Delta_S_obs[t] - cromosoma_u[t]#-Evap_TCM[t]

        # RESTRICCIÓN FÍSICA: No se puede liberar volumen negativo
        if R_obs[t] + cromosoma_u[t] < 0:
            return (float('1e10'),)

        # RESTRICCIÓN FÍSICA: Capacidad de la presa
        if S_opt[t+1] < 0 or S_opt[t+1] > S_max:
            return (float('1e10'),)

    # Penalizaciones (Soft Constraints)
    C_crit = np.sum([max(0, S_min - S_opt[t])**2 for t in range(T+1)])
    C_dev = np.sum(cromosoma_u**2)
    C_smooth = np.sum(np.diff(cromosoma_u)**2)

    # Ponderaciones
    w1 = 1 / ((T + 1) * (S_min**2))
    #w2 = 0.000001 / (T * (u_max**2))
    w2 = 0.1 / (T * (u_max**2))
    w3 = 0.1 / ((T - 1) * ((2 * u_max)**2))

    SRS = (w1 * C_crit) + (w2 * C_dev) + (w3 * C_smooth)
    return (SRS,)

toolbox.register("evaluate", evaluar_srs)

# =========================================================
# 6. OPERADORES GENÉTICOS
# =========================================================
toolbox.register("mate", tools.cxTwoPoint)

def mutar_nivel(individuo, indpb):
    for i in range(len(individuo)):
        if random.random() < indpb:
            individuo[i] = random.choice(NIVELES_PERMITIDOS)
    return individuo,

toolbox.register("mutate", mutar_nivel, indpb=0.15)
toolbox.register("select", tools.selTournament, tournsize=4)

# =========================================================
# 7. EJECUCIÓN
# =========================================================
def correr_modelo():
    pop = toolbox.population(n=500)

    # INYECCIÓN DEL ÓPTIMO CONOCIDO (Seeding)
    # Crea un individuo con puros ceros para garantizar una línea base factible
    individuo_base = creator.Individual([0.0] * T)
    pop[0] = individuo_base

    hof = tools.HallOfFame(1)
    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("min", np.min)
    stats.register("avg", np.mean)

    print("Iniciando evolución...")
    pop, log = algorithms.eaSimple(pop, toolbox, cxpb=0.7, mutpb=0.2, ngen=150,
                                   stats=stats, halloffame=hof, verbose=True)

    mejor_solucion = hof[0]

    print("\n" + "="*50)
    print(" RESULTADOS DE LA OPTIMIZACIÓN (DEAP)")
    print("="*50)

    score_final = mejor_solucion.fitness.values[0]
    if score_final >= 1e9:
        print("ADVERTENCIA: El modelo no pudo mejorar la línea base y sigue violando restricciones.")
    else:
        print(f"Mejor Score (SRS): {score_final:.4f}")

    print(f"Desviación de Volumen Total (Límite 10%): {abs(np.sum(mejor_solucion)) / np.sum(R_obs) * 100:.2f}%\n")

    print("Secuencia Óptima de Ajustes u(t):")
    # Imprimir vector de forma legible
    print(np.array(mejor_solucion).round(2))

    return pop, log, hof, mejor_solucion

if __name__ == "__main__":
    poblacion_final, estadisticas, salon_de_la_fama, mejor_secuencia = correr_modelo()

def auditar_restricciones(secuencia_u, R_obs, Delta_S_obs, S_inicial, S_max, niveles_permitidos):
    """
    Somete la solución final a una auditoría estricta contra las restricciones del benchmark.
    """
    print("\n" + "═"*55)
    print(" 🔎 AUDITORÍA DE RESTRICCIONES (COMPLIANCE CHECK)")
    print("═"*55)

    T = len(secuencia_u)
    S_opt = np.zeros(T + 1)
    S_opt[0] = S_inicial
    fallos = 0

    # 1. Chequeo de Niveles Discretos (Diseño por construcción)
    # Verifica que el modelo cuántico/genético no haya inventado valores intermedios
    niveles_validos = all(np.isclose(u, niveles_permitidos, atol=1e-5).any() for u in secuencia_u)
    print(f"[1] Niveles de decisión discretos válidos : {'✅ PASÓ' if niveles_validos else '❌ FALLÓ'}")
    if not niveles_validos: fallos += 1

    # 2. Chequeo de Balance Acumulado (Restricción Global del 10%)
    desviacion_total = abs(np.sum(secuencia_u))
    volumen_historico = np.sum(R_obs)
    limite_10_porciento = 0.10 * volumen_historico
    balance_valido = desviacion_total <= limite_10_porciento

    print(f"[2] Balance Acumulado (Límite 10%)        : {'✅ PASÓ' if balance_valido else '❌ FALLÓ'}")
    print(f"    ├─ Desviación propuesta  : {desviacion_total:,.1f} TCM")
    print(f"    └─ Límite máximo (10%)   : {limite_10_porciento:,.1f} TCM")
    if not balance_valido: fallos += 1

    # Variables para rastrear fallos físicos a lo largo del tiempo
    flujo_negativo = False
    desborde = False
    sequia = False

    # 3 y 4. Simulador de Chequeos Físicos paso a paso
    for t in range(T):
        # Flujo de liberación
        flujo_actual = R_obs[t] + secuencia_u[t]
        if flujo_actual < 0:
            flujo_negativo = True

        # Transición del embalse
        S_opt[t+1] = S_opt[t] + Delta_S_obs[t] - secuencia_u[t]
        if S_opt[t+1] > S_max:
            desborde = True
        if S_opt[t+1] < 0:
            sequia = True

    print(f"[3] No-negatividad del flujo (R(t) >= 0)  : {'❌ FALLÓ (Flujo < 0 detectado)' if flujo_negativo else '✅ PASÓ'}")
    if flujo_negativo: fallos += 1

    print(f"[4] Límite inferior del embalse (S >= 0)  : {'❌ FALLÓ (Nivel < 0 detectado)' if sequia else '✅ PASÓ'}")
    if sequia: fallos += 1

    print(f"[5] Límite superior embalse (S <= S_max)  : {'❌ FALLÓ (Desborde detectado)' if desborde else '✅ PASÓ'}")
    if desborde: fallos += 1

    print("-" * 55)
    if fallos == 0:
        print("🚀 DICTAMEN FINAL: La secuencia es 100% FACTIBLE.")
        print("   Cumple con todas las reglas operativas del benchmark.")
    else:
        print(f"⚠️ DICTAMEN FINAL: Solución INVIABLE. Se detectaron {fallos} violaciones.")
    print("═"*55 + "\n")

# Ejecutar la auditoría pasándole los resultados de tu modelo
# Asegúrate de llamar esta función al final de tu script principal
auditar_restricciones(mejor_secuencia, R_obs, Delta_S_obs, S_inicial, S_max, NIVELES_PERMITIDOS)
